# Generated by Django 3.0.1 on 2020-01-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='users/default-avatar.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
