# Generated by Django 3.0.1 on 2020-01-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200127_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='users/default.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
