# Generated by Django 3.0.1 on 2019-12-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190923_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
