# Generated by Django 3.0.1 on 2019-12-26 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tests.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', tests.fields.OrderField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('text', models.TextField()),
                ('right_answer', models.PositiveIntegerField(default=0)),
                ('question_commentory', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('len', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', tests.fields.OrderField(blank=True)),
                ('text', models.CharField(max_length=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='tests.Page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='tests.Test'),
        ),
    ]
