# Generated by Django 3.0.1 on 2020-01-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20191226_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='right_answer',
            field=models.CharField(max_length=10),
        ),
    ]
