# Generated by Django 3.0.1 on 2020-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20200111_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='right_answer',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
