# Generated by Django 3.0.1 on 2020-01-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20200111_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='right_answer',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
