# Generated by Django 3.0.1 on 2020-01-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20200111_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
