# Generated by Django 3.0.1 on 2020-01-16 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0006_auto_20200116_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='test_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
