# Generated by Django 3.0.1 on 2020-01-25 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0008_auto_20200116_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='users_dislike',
            field=models.ManyToManyField(blank=True, related_name='test_disliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
