# Generated by Django 3.0.1 on 2020-01-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20200127_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-result']},
        ),
    ]
